# Generated by Django 5.1.4 on 2025-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news_app', '0005_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
